apiVersion: v1
kind: Service
metadata:
  name: testcowproject
spec:
  selector:
    app: nginx  # Updated to match the label in your deployment
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
  type: LoadBalancer
